import "./globals.css";
import SmoothScrolling from "./utility/SmoothScrolling";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScrolling>
          <div>{children}</div>
        </SmoothScrolling>
      </body>
    </html>
  );
}
